### ISSUE TITLE
如何才能配置成功啊？失败N次了。

### ISSUE THREAD

**Issue by nwtown** [lavas-project/vue-skeleton-webpack-plugin#11]
单页面  
node_modules\memory-fs\lib\MemoryFileSystem.js:114
                        throw new MemoryFileSystemError(errors.code.ENOENT, _path);

就报这个错。快疯了。求解

**Comment by PengXing** [comment]
能再详细点吗？

**Comment by xiaoiver** [comment]
给 Skeleton 使用的 Webpack 配置，由于需要把用到的 CSS 从 JS 里分离出来，所以必须要使用 ExtractTextPlugin 这个插件。

如果你是用 vue-cli 创建的项目，默认情况下只有在 `production` 模式下才会开启这个插件。如果你给 Skeleton 使用的 Webpack 配置不作任何修改，只是简单 merge，在 `development` 模式下就会出错。

这里有一个[示例项目](https://github.com/xiaoiver/multi-skeleton-demo)，也是用 vue-cli 创建的。
注意[这一段](https://github.com/xiaoiver/multi-skeleton-demo/blob/master/build/webpack.skeleton.conf.js#L33-L37)：
```javascript
// webpack.skeleton.conf

// 开启 Skeleton 的样式分离
skeletonWebpackConfig.module.rules[0].options.loaders = utils.cssLoaders({
  sourceMap: sourceMapEnabled,
  extract: true
}),
```

这是[实际效果](https://xiaoiver.github.io/multi-skeleton-demo/#/)

**Comment by nwtown** [comment]
谢谢，我去试试 。刚接触webpack 以前就是cli后也没改过。

**Comment by nwtown** [comment]
项目使用了vux,配置完vux-loader后就会提示 
‘’‘
TypeError: Cannot set property 'loaders' of undefined
 at Object.<anonymous> (E:\webroot\multi-skeleton-demo\build\webpack.skeleton.conf.js:34:55)
’‘’
我也是醉了。。 这插件用的人很少？ 找不到有用的信息。

**Comment by xiaoiver** [comment]
@nwtown ，先别醉。。。建议先了解一下 Webpack 关于[模块](https://doc.webpack-china.org/configuration/module/)的配置

**Comment by nwtown** [comment]
@xiaoiver 感谢这么详细的回复，受教了，我去弄。再有问题再请教！ 您是一个好人。

**Comment by Ziming98** [comment]
![image](https://user-images.githubusercontent.com/38863980/39961520-601a9946-566a-11e8-95c5-d94d3c1e4be2.png)
我也很绝望啊。。。。已经开启extract: true

**Comment by liverwang** [comment]
@Ziming98 注意dev换行开启样式分离后，需要再webpack.dev.conf.js文件中完善extract-text-webpack-plugin插件的配置，具体可以直接拷贝webpack.prod.conf.js的配置
`const ExtractTextPlugin = require('extract-text-webpack-plugin')`
`// extract css into its own file
    new ExtractTextPlugin({
      filename: utils.assetsPath('css/[name].[contenthash].css'),
      // Setting the following option to `false` will not extract CSS from codesplit chunks.
      // Their CSS will instead be inserted dynamically with style-loader when the codesplit chunk has been loaded by webpack.
      // It's currently set to `true` because we are seeing that sourcemaps are included in the codesplit bundle as well when it's `false`,
      // increasing file size: https://github.com/vuejs-templates/webpack/issues/1110
      allChunks: true,
    })`

**Comment by LNyears** [comment]
开启样式分离无效，写内联样式可以，这是什么情况啊 ？
webpack.dev.conf.js也配置了像你说的：
 // extract css into its own file
    new ExtractTextPlugin({
      filename: utils.assetsPath('css/[name].[contenthash].css'),
      // Setting the following option to `false` will not extract CSS from codesplit chunks.
      // Their CSS will instead be inserted dynamically with style-loader when the codesplit chunk has been loaded by webpack.
      // It's currently set to `true` because we are seeing that sourcemaps are included in the codesplit bundle as well when it's `false`,
      // increasing file size: https://github.com/vuejs-templates/webpack/issues/1110
      allChunks: true
    }),
webpack.skeleton.conf.js也开启了：

// important: enable extract-text-webpack-plugin
skeletonWebpackConfig.module.rules[0].options.loaders = utils.cssLoaders({
  sourceMap: sourceMapEnabled,
  extract: true
}),
就是样式分离不了，求解救啊老师

**Comment by LNyears** [comment]
webpack.skeleton.conf.js文件完整配置如下：
'use strict';

const path = require('path')
const merge = require('webpack-merge')
const baseWebpackConfig = require('./webpack.base.conf')
const nodeExternals = require('webpack-node-externals')
const utils = require('./utils')
const config = require('../config')
const isProduction = process.env.NODE_ENV === 'production'
const sourceMapEnabled = isProduction
  ? config.build.productionSourceMap
  : config.dev.cssSourceMap

function resolve(dir) {
  return path.join(__dirname, dir)
}

let skeletonWebpackConfig = merge(baseWebpackConfig, {
  target: 'node',
  devtool: false,
  entry: {
    app: resolve('../src/Skeleton/entry-skeleton.js')
  },
  output: Object.assign({}, baseWebpackConfig.output, {
    libraryTarget: 'commonjs2'
  }),
  externals: nodeExternals({
    whitelist: /\.css$/
  }),
  plugins: []
})

// important: enable extract-text-webpack-plugin
skeletonWebpackConfig.module.rules[0].options.loaders = utils.cssLoaders({
  sourceMap: sourceMapEnabled,
  extract: true
}),

module.exports = skeletonWebpackConfig

webpack.dev.conf.js 文件关于骨架的配置如下：
 // inject skeleton content(DOM & CSS) into HTML
    new SkeletonWebpackPlugin({
      webpackConfig: require('./webpack.skeleton.conf'),
      quiet: true,
      minimize: true,
      router: {
        mode: 'history',
        routes: [
          // {
          //   path: '',
          //   skeletonId: 'skeleton-investmentfinancehome'
          // },
          {
            path: '',
            skeletonId: 'skeleton1'
          },
          {
            path: '/InvestmentFinance',
            skeletonId: 'skeleton-investmentfinancehome'
          },
          {
            path: '/InvestmentFinance/FinanceSubMenu/more',
            skeletonId: 'skeleton-financesubmenu-more'
          },
          {
            path: '/InvestmentFinance/WalletHome',
            skeletonId: 'skeleton-wallethome'
          }
        ]
      }
    }),
老师麻烦帮忙看看，在线等，谢谢！

**Comment by liverwang** [comment]
建议你可以尝试将【vue-loader.conf.js】文件中的loaders配置直接改成

loaders: utils.cssLoaders({
sourceMap: sourceMapEnabled,
extract: true // 因为使用Skeleton，需要分离样式文件，这里直接选择true
}),


因为在【webpack.skeleton.conf.js】中修改的[0]有可能是第一个了

skeletonWebpackConfig.module.rules[0].options.loaders


Best Regards
Liver.Wang @小木匠
Mail: live_wang@live.cn


________________________________
发件人: LNyears <notifications@github.com>
发送时间: 2018年6月8日 4:00
收件人: lavas-project/vue-skeleton-webpack-plugin
抄送: liverwang; Comment
主题: Re: [lavas-project/vue-skeleton-webpack-plugin] 如何才能配置成功啊？失败N次了。 (#11)


webpack.skeleton.conf.js文件完整配置如下：
'use strict';

const path = require('path')
const merge = require('webpack-merge')
const baseWebpackConfig = require('./webpack.base.conf')
const nodeExternals = require('webpack-node-externals')
const utils = require('./utils')
const config = require('../config')
const isProduction = process.env.NODE_ENV === 'production'
const sourceMapEnabled = isProduction
? config.build.productionSourceMap
: config.dev.cssSourceMap

function resolve(dir) {
return path.join(__dirname, dir)
}

let skeletonWebpackConfig = merge(baseWebpackConfig, {
target: 'node',
devtool: false,
entry: {
app: resolve('../src/Skeleton/entry-skeleton.js')
},
output: Object.assign({}, baseWebpackConfig.output, {
libraryTarget: 'commonjs2'
}),
externals: nodeExternals({
whitelist: /.css$/
}),
plugins: []
})

// important: enable extract-text-webpack-plugin
skeletonWebpackConfig.module.rules[0].options.loaders = utils.cssLoaders({
sourceMap: sourceMapEnabled,
extract: true
}),

module.exports = skeletonWebpackConfig

webpack.dev.conf.js 文件关于骨架的配置如下：
// inject skeleton content(DOM & CSS) into HTML
new SkeletonWebpackPlugin({
webpackConfig: require('./webpack.skeleton.conf'),
quiet: true,
minimize: true,
router: {
mode: 'history',
routes: [
// {
// path: '',
// skeletonId: 'skeleton-investmentfinancehome'
// },
{
path: '',
skeletonId: 'skeleton1'
},
{
path: '/InvestmentFinance',
skeletonId: 'skeleton-investmentfinancehome'
},
{
path: '/InvestmentFinance/FinanceSubMenu/more',
skeletonId: 'skeleton-financesubmenu-more'
},
{
path: '/InvestmentFinance/WalletHome',
skeletonId: 'skeleton-wallethome'
}
]
}
}),
老师麻烦帮忙看看，在线等，谢谢！

―

**Comment by BryanAdamss** [comment]
> ![image](https://user-images.githubusercontent.com/38863980/39961520-601a9946-566a-11e8-95c5-d94d3c1e4be2.png)
> 我也很绝望啊。。。。已经开启extract: true

开启后，遇到同样问题

**Comment by lazcy** [comment]
按照文章提到的方式配置了，运行也没有问题，但是看不到骨架屏的效果，为啥呢

**Comment by sechours** [comment]
- 
![_20190220140808](https://user-images.githubusercontent.com/23120165/53070300-a5957200-3519-11e9-9076-1b16f8718934.png)
![_20190220140816](https://user-images.githubusercontent.com/23120165/53070301-a62e0880-3519-11e9-99db-b1041f57188e.png)
![_20190220140819](https://user-images.githubusercontent.com/23120165/53070302-a62e0880-3519-11e9-811b-fb65f6544dd0.png)
![_20190220140822](https://user-images.githubusercontent.com/23120165/53070303-a6c69f00-3519-11e9-812e-8761a2f9a432.png)
![_20190220140826](https://user-images.githubusercontent.com/23120165/53070305-a6c69f00-3519-11e9-84f2-85a46854f845.png)

**Comment by ihamlet** [comment]
我跟你一样出现了这样的问题
 将样式当做变量运行了  按照楼上配置一上午

**Comment by chencmgithub** [comment]
![image](https://user-images.githubusercontent.com/18524929/56877562-7f440380-6a81-11e9-995c-04967e9547fc.png)

怎么解决？？dev模式下没问题，pro模式下就报错，关闭 usePostCSS: false就OK。但是这样的话postCSS就用不了，项目中需要将px转为rem。
