### ISSUE TITLE
[bug] build: 一直在loading

### ISSUE THREAD

**Issue by myronliu347** [lavas-project/vue-skeleton-webpack-plugin#12]
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Path must be a string. Received undefined
(node:37146) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

项目中使用到了HappyPack 不知道会不会有影响

**Comment by easonyq** [comment]
你是在使用 lavas 时候碰上的这个报错还是单独使用 vue-skeleton-webpack-plugin 时？

如果是使用 lavas 时，你是如何定位到这个插件来的呢？

这个报错看上去就是在使用 path 的相关接口时，应该传路径的地方传了 undefined，但具体堆栈没有，不好说究竟错在哪里，需要更多的信息才能定位。

**Comment by myronliu347** [comment]
我找到问题了，总算是成功，

**Comment by easonyq** [comment]
不如也在这儿分享下？？
