### ISSUE TITLE
骨架屏如何解决SEO问题？

### ISSUE THREAD

**Issue by chesscai** [lavas-project/vue-skeleton-webpack-plugin#14]
pre-render:
``` html
<body>
  <div id="app><skeleton-dom /></div>
</body>
```

init:
``` html
<body>
  <div id="app><render-dom /></div>
</body>
```

**Comment by easonyq** [comment]
骨架屏目前适用于单页/多页应用，这两种都是 __前端渲染__的方式。

从 SEO 的角度来说，只要是前端渲染的页面，总还是依赖 js 执行才能出正确的结果。如果脱离 js，不管是不是有骨架屏，其实都对 SEO 是不利的。

也因此类似 prerenderer 或者 SSR (服务端渲染) 之类的技术才应运而生。

**Comment by easonyq** [comment]
你好，鉴于你的 ISSUE 描述非常简略，我只能揣测你的实际问题，从两个可能的方面来回答。

## 普通情况

skeleton 是作用于单页/多页应用的，而这两者均为 **前端渲染**，即通过 JS 的执行往一个空的容器节点中插入实际的 HTML。

从 SEO 的角度来看，如果一个 **直接抓取 HTML 不执行 JS 的** 搜索引擎访问前端渲染的站点，在不带 skeleton 的时候，它看到的应该是

```html
<body>
    <div id="app"></div>
</body>
```

而增加了 skeleton 功能后，它看到的应该是

```html
<body>
    <div id="app"><skeleton-dom /></div>
</body>
```

因此**是否增加骨架屏对于 SEO 来说都是没有帮助且没有坏处的**。如果您需要解决 SEO，应该考虑将整站改为服务端渲染（SSR）或者使用预渲染 (prerendering) 技术。

## prerendering

鉴于你的 issues 中也提到了这个单词，我不确定你的意思是不是在问**使用预渲染技术是否会导致骨架屏影响 SEO**。如果的确是这个问题，那答案依然是：**不会**。

原因也很简单，Vue 官方推荐的预渲染插件是 [prerender-spa-plugin](https://github.com/chrisvfritz/prerender-spa-plugin)，这个插件会在编译时启动浏览器环境，访问特定页面，并产出静态 HTML 以解决 SEO。因此这里产出的 HTML 其实已经是**渲染后**的结果了，骨架屏内容**并不会**包含在内。

## 总结

总结两种情况，骨架屏并不会对 SEO 产生任何影响，无论是正向还是负向。

**Comment by chesscai** [comment]
你好，感谢你的详细解答。抱歉，提问太粗糙。
对于“普通情况”没有问题；
提问的是，考虑SEO的情况下（既SSR或prerendering）：
  1. 直接返回渲染后的静态html
  2. 通过asyncData或fetch返回带异步数据的html

是否这两种情况下已经没有使用骨架屏的需要了，骨架屏只适用于前端渲染？

**Comment by PengXing** [comment]
是的，你回答的对，前端渲染才需要骨架屏
