### ISSUE TITLE
是否有demo线上能访问下?

### ISSUE THREAD

**Issue by ai-ruby** [lavas-project/vue-skeleton-webpack-plugin#2]
请问有具体的demo或者说明具体怎么使用您的插件呢?恕我愚昧,研究两三天还没看懂具体怎么操作实现功能,谢谢!

**Comment by xiaoiver** [comment]
https://lavas.baidu.com/demo 这里有线上的demo，可以参考下。项目里examples文件夹里也有单页和多页的示例。另外有什么具体问题可以在这里说下

**Comment by hua1995116** [comment]
能否上传一个像你示例效果那样的例子，你这个只是生成一个首页是吗？然后再按照正常的逻辑写？
