### ISSUE TITLE
多页面项目里面不一定每个页面都有skeleton

### ISSUE THREAD

**Issue by zengyuangai** [lavas-project/vue-skeleton-webpack-plugin#23]
多页面项目里面不一定有每个页面有对应的skeleton
                // find current processing entry
                if (Array.isArray(usedChunks)) {
                    entryKey = Object.keys(skeletonEntries).find(v => usedChunks.indexOf(v) > -1);
                }
                else {
                    entryKey = DEFAULT_ENTRY_NAME;
                }
这样会有问题 undefined...

**Comment by zengyuangai** [comment]
@PengXing  期待能修复

**Comment by PengXing** [comment]
这个作者这周休假了，让他下周来帮你看一下啊

**Comment by zengyuangai** [comment]
好的 @PengXing  有劳 感谢

**Comment by zengyuangai** [comment]
@PengXing  不知道修复了么

**Comment by zengyuangai** [comment]
@PengXing  提了个pr https://github.com/lavas-project/vue-skeleton-webpack-plugin/pull/27 有空看看

**Comment by xiaoiver** [comment]
已经修复了哈，更新到 `1.1.18` 版本就行了

**Comment by zengyuangai** [comment]
@xiaoiver  赞

**Comment by martinko2009** [comment]
具体怎么用呢

**Comment by PengXing** [comment]
https://github.com/lavas-project/vue-skeleton-webpack-plugin

文档里写了
