### ISSUE TITLE
SkeletonWebpackPlugin中的insertAfter 选填，能否自动的根据不同的页面，自动设置不同的id值

### ISSUE THREAD

**Issue by martinko2009** [lavas-project/vue-skeleton-webpack-plugin#26]
SkeletonWebpackPlugin中的insertAfter 选填，渲染 DOM 结果插入位置，默认值为'<div id="app">'，
由于是多页应用，所以每个页面中的vue的挂载id的值，会根据不同的页面，id的值会不同，
能否自动的根据不同的页面，自动设置不同的id值比如'<div id="'+[name]+'">'

**Comment by xiaoiver** [comment]
谢谢你的反馈。

**Comment by martinko2009** [comment]
是的

**Comment by xiaoiver** [comment]
@martinko2009 ，`insertAfter` 支持传入 `Function`，方法签名是 `insertAfter(entryKey: string): string`，这样在上述场景下可以这么做：
```javascript
insertAfter: entryKey => `<div id='app-${entryKey}'>`;
```
