### ISSUE TITLE
npm run test出现错误

### ISSUE THREAD

**Issue by xiaobinwu** [lavas-project/vue-skeleton-webpack-plugin#3]
报错呢，好像是有个命令错了

> vue-skeleton-webpack-plugin@1.1.5 test E:\git\vue-skeleton-webpack-plugin
> npm run build && ./node_modules/.bin/nyc ava

> vue-skeleton-webpack-plugin@1.1.5 build E:\git\vue-skeleton-webpack-plugin
> buble src -o lib

'.' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! vue-skeleton-webpack-plugin@1.1.5 test: `npm run build && ./node_modules/.bin/nyc ava`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue-skeleton-webpack-plugin@1.1.5 test script 'npm run build && ./node_modules/.bin/nyc ava'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the vue-skeleton-webpack-plugin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build && ./node_modules/.bin/nyc ava
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs vue-skeleton-webpack-plugin
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls vue-skeleton-webpack-plugin
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\git\vue-skeleton-webpack-plugin\npm-debug.log

**Comment by xiaoiver** [comment]
`"scripts": {
    ...
    "test": "npm run build && nyc ava"
  },`

**Comment by Gutwql** [comment]
遇到一样的报错，本地路径是有./node_modules/.bin/nyc的，改成"scripts": { ... "test": "npm run build && nyc ava" },也不行
