### ISSUE TITLE
修改文件重新编译时，构建生成的文件并没有更改？

### ISSUE THREAD

**Issue by vifird** [lavas-project/vue-skeleton-webpack-plugin#33]
使用`extract-text-webpack-plugin`监听骨架屏的文件，文件更改时，重新进行编译，但是这时候骨架屏生成的文件并没有更新，这个是什么原因呢？

**Comment by xiaoiver** [comment]
HotReload 需要依赖 html-webpack-plugin，目前我也在研究，
后续可以关注这个 ISSUE #20

**Comment by vifird** [comment]
@xiaoiver 发现超过50s后更改文件，ssr生成的html可以更新，50s内更新不可以。不使用childCompiler，使用新的webpack编译是OK的。

**Comment by xiaoiver** [comment]
@vifird ，最新的 `1.2.1` 已经支持 hot reload 了，现在修改 skeleton 文件。
原有的在开发模式下通过 `loaders` 配置项添加路由的做法可以去掉了。

**Comment by vifird** [comment]
@xiaoiver 赞👍
