### ISSUE TITLE
请问vue-cli3.0构建的项目注入的html和css如何压缩？

### ISSUE THREAD

**Issue by leiyaguang** [lavas-project/vue-skeleton-webpack-plugin#36]
请问vue-cli3.0构建的项目注入的html和css如何压缩？

**Comment by xiaoiver** [comment]
`html-webpack-plugin` 会压缩注入的 HTML，但是内联的 CSS 并不会。
所以可以考虑下[style-ext-html-webpack-plugin](https://github.com/numical/style-ext-html-webpack-plugin)。

**Comment by twoer** [comment]
@xiaoiver 

```
new HtmlWebpackPlugin({
            minify: {
                removeComments: true,
                collapseWhitespace: true,
                removeAttributeQuotes: true,
                minifyCSS: true // 压缩内联的 CSS
            }
        }),
```


vue cli 3.0 的项目里面，这段代码具体配置在什么位置，我配置后，发现 html 压缩了，但是 css 没有压缩，麻烦指点一下。
