### ISSUE TITLE
SPA 中多路由正则生成有误

### ISSUE THREAD

**Issue by xiaoiver** [lavas-project/vue-skeleton-webpack-plugin#45]
## 问题描述

相关 ISSUE #18 

SPA 多路由多个 Skeleton 情况下 `path` 参数可以是字符串或者正则。
当填写字符串例如 `/page1` 时，内部转成的正则是 `/^\/page1(?:\/)?$/i`，无法匹配 `/page1?a=1` 这样的路由路径。

## 问题原因

使用 [path-to-regexp](https://github.com/pillarjs/path-to-regexp) 将字符串转正则，默认情况下 `end: true` 会要求匹配结尾，这就导致 `/page1` 无法匹配带参数的情况了。

## 解决方法

两种方式：
1. `path` 参数直接使用正则 `path: /^\/page1/`
2. `path` 参数继续使用字符串，内部转换成正则时 `end: false`

**Comment by OrangeHeap** [comment]
麻烦问下对于路由内包含params的该如何匹配，比如router中的路径是/page1/:id此时还是path: /^\/page1/么？

**Comment by PengXing** [comment]
应该是前者

**Comment by OrangeHeap** [comment]
好的多谢

**Comment by martinko2009** [comment]
对于SPA来说，如果router.routes[{path:"/path"}], 他匹配的是vue-route中/path的路径，如果不是/path路径，是不是就不显示骨架屏了。
因为我的SPA，不是所有的页面都需要骨架屏的。
@xiaoiver @easonyq
