### ISSUE TITLE
安装后提示vue、vue-server-renderer版本不匹配

### ISSUE THREAD

**Issue by huaganshang** [lavas-project/vue-skeleton-webpack-plugin#48]
安装完,运行报错，如下；
Error:
Vue packages version mismatch:
- vue@2.5.16
- vue-server-renderer@2.5.17

安装包版本：
“webpack": 3.12.0
"vue-skeleton-webpack-plugin": "1.2.2";

谢谢了；

**Comment by OrangeHeap** [comment]
请问您是如何解决的？
