### ISSUE TITLE
loader.js

### ISSUE THREAD

**Issue by xiaobinwu** [lavas-project/vue-skeleton-webpack-plugin#5]
// insert import sentence in the head
source += importExpression;
这里 组件import插到source的尾部，不会出现问题吗？

**Comment by xiaoiver** [comment]
恩，按照 ES Module 的规范，import 是会被提升的，所以写在末尾也不会有问题。所以 Webpack 在实现中也遵循规范。[相关 ISSUE](https://github.com/webpack/webpack/issues/4120#issuecomment-276160928)

**Comment by xiaobinwu** [comment]
ERROR in ./src/router/foo.js
Module build failed: SyntaxError: E:/git/my-vue-scaffold/src/router/foo.js: Unexpected token, expected ; (22:2)

  20 | export default new VueRouter({
  21 |     routes
> 22 | })import Foo from '~/skeleton/foo/skeleton.vue'

觉得这里可以加个换行，不然有的地方会出错！
source += "\n" + importExpression;

**Comment by xiaoiver** [comment]
新的版本 v1.1.7 已经修复了这个问题。其实很多编辑器都会在文件末尾自动添加一个空行的。
