### ISSUE TITLE
没有将渲染后的dom插入到html中

### ISSUE THREAD

**Issue by LeoZeda** [lavas-project/vue-skeleton-webpack-plugin#51]
编译没有通过后，没有将渲染后的dom元素插入到index.html中，只是有一个注释的函数function (a, b, c, d) { return createElement(vm, a, b, c, d, true); }

![image](https://user-images.githubusercontent.com/8565999/48458801-c5bee200-e802-11e8-8676-bf4c9bde91ce.png)

**Comment by LeoZeda** [comment]
是我问题没有描述清楚吗？
情况是这样的，想在项目中添加骨架页面，按照要求配置，运行后，没有出现骨架页面。然后发现index.html有一个注释的函数function (a, b, c, d) { return createElement(vm, a, b, c, d, true); }，应该是用于骨架渲染的。
后来通过跑一些demo例子，可以出现骨架页面，返回的index.html文件是这样的(如下图)
![image](https://user-images.githubusercontent.com/8565999/48464625-23f7bf00-e81b-11e8-8770-78bea311c690.png)

是项目中得库版本不同产生的冲突？

**Comment by LeoZeda** [comment]
function (a, b, c, d) { return createElement(vm, a, b, c, d, true); }这个函数要到那一步才渲染？

**Comment by LeoZeda** [comment]
找到问题了，是entry的问题……

**Comment by PengXing** [comment]
嗯，不好意思了，最开始关掉是因为没描述清楚，既然解决问题了，那也就不打开了
