### ISSUE TITLE
vue、vue-server-renderer版本不匹配问题

### ISSUE THREAD

**Issue by OrangeHeap** [lavas-project/vue-skeleton-webpack-plugin#55]
目前安装完vue-skeleton-webpack-plugin启动时，会报以下错误
Vue packages version mismatch:

- vue@2.5.2
- vue-server-renderer@2.5.17

webpack版本号为：2.3.3

目前不希望升级vue版本，请问可否解决该问题？

**Comment by PengXing** [comment]
因为 vue-skeleton-webpack-plugin 生成 skeleton 的代码时，使用到了 SSR，也就是  vue-server-renderer，因为这个必须

你可以在你项目里把对应版本的 vue-server-renderer 加到 package.json devDependencies 试试

**Comment by OrangeHeap** [comment]
已解决问题，导致问题的原因是yarn.lock内的锁死版本是2.5.17，如果有和我一样问题的朋友，请仔细查看yarn.lock的锁死版本
