### ISSUE TITLE
请问如何针对多页面的不同路由进行配置？

### ISSUE THREAD

**Issue by defypro** [lavas-project/vue-skeleton-webpack-plugin#57]
例如：a.html/#/home和b.html/#/home

**Comment by defypro** [comment]
`
        if (isMPA) {
            routes = routes.filter(route => route.entryName === entryName);
        }
`

看到了这段代码，`entryName`是否是用来区分不同入口下的路由

**Comment by PengXing** [comment]
从代码上看来，是不支持的

**Comment by defypro** [comment]
已经测试过了，是可以的。
文档中只是说明了`routes`支持 `path `和`skeletonId `两个参数，其实还可以添加`entryName `参数用来区分不同入口的路由。不过作者并没有更新到文档上去，不知道是否是有其他的考虑。
