### ISSUE TITLE
配置好后可以使用，但是在skeleton.vue里面无法使用alert，navigator等对象方法

### ISSUE THREAD

**Issue by alicksnake22** [lavas-project/vue-skeleton-webpack-plugin#58]
希望在skeleton.vue里面判断安卓还是ios，以生成不同的骨架屏，但是提示navigator is not defined，并且building卡住

**Comment by PengXing** [comment]
骨架屏是通过运行 SSR 自动生成的，SSR 时，没有 navigator 这些变量，所以会报错

**Comment by alicksnake22** [comment]
是的，谢谢
