### ISSUE TITLE
关于vue-cli3 多skeleton 多路由的问题

### ISSUE THREAD

**Issue by zhoufanglu** [lavas-project/vue-skeleton-webpack-plugin#83]
* 不同路由页面 显示 不同的skeleton 
* 为单页面模式
* `router`为`hash`模式

```js
// - Skeleton.js
import Vue from 'vue';
import Skeleton1 from './Skeleton1.vue';
import Skeleton2 from './Skeleton2.vue';

export default new Vue({
  components: {
    Skeleton1,
    Skeleton2,
    /*template: `
        <div>
            <skeleton1 id="skeleton1" style="display:none"/>
            <skeleton2 id="skeleton2" style="display:none"/>
        </div>
    `,*/
  },
  render: h => h(Skeleton1,Skeleton2),
});
```

`vue.config.js`
```js
config.plugins.push(new SkeletonWebpackPlugin({
      webpackConfig: {
        entry: {
          app: path.join(__dirname, './src/skeleton/entry-skeleton.js'),
        },
        router: {
          mode: 'hash',
          routes: [
            {
              path: '/test',
              skeletonId: 'skeleton1'
            },
            {
              path: '/home',
              skeletonId: 'skeleton2'
            }
          ]
        }
      },
      minimize: true,
      quiet: true,
    }))
```

无论是在`test.vue`还是`home.vue`  永远显示的是`skeleton1`
请问哪里写错了？

**Comment by luobinhang** [comment]
```javascript
// - Skeleton.js
import Vue from 'vue';
import Skeleton1 from './Skeleton1.vue';
import Skeleton2 from './Skeleton2.vue';

export default new Vue({
  components: {
    Skeleton1,
    Skeleton2
  },
 template: `
       <div style='height: 100%;'>
           <Skeleton1 id="skeleton1" style="display:none"/>
           <Skeleton2 id="skeleton2" style="display:none"/>
       </div>
    `
});
```

改成这样试试

**Comment by zhoufanglu** [comment]
> ```js
> // - Skeleton.js
> import Vue from 'vue';
> import Skeleton1 from './Skeleton1.vue';
> import Skeleton2 from './Skeleton2.vue';
> 
> export default new Vue({
>   components: {
>     Skeleton1,
>     Skeleton2
>   },
>  template: `
>        <div style='height: 100%;'>
>            <Skeleton1 id="skeleton1" style="display:none"/>
>            <Skeleton2 id="skeleton2" style="display:none"/>
>        </div>
>     `
> });
> ```
> 
> 改成这样试试

改成这样 连skeleton组件都不显示了  请问你vue.config怎么写的？

**Comment by luobinhang** [comment]
> > ```js
> > // - Skeleton.js
> > import Vue from 'vue';
> > import Skeleton1 from './Skeleton1.vue';
> > import Skeleton2 from './Skeleton2.vue';
> > 
> > export default new Vue({
> >   components: {
> >     Skeleton1,
> >     Skeleton2
> >   },
> >  template: `
> >        <div style='height: 100%;'>
> >            <Skeleton1 id="skeleton1" style="display:none"/>
> >            <Skeleton2 id="skeleton2" style="display:none"/>
> >        </div>
> >     `
> > });
> > ```
> > 
> > 
> > 改成这样试试
> 
> 改成这样 连skeleton组件都不显示了 请问你vue.config怎么写的？

```javascript
 new SkeletonWebpackPlugin({
      webpackConfig: {
        entry: {
          app: path.join(__dirname, './src/skeleton/entry.ts'),
        },
      },
      minimize: true,
      router: {
        mode: 'hash',
        routes: [
          { path: '', skeletonId: 'HomeSkeleton' },
          { path: '/', skeletonId: 'HomeSkeleton' },
          { path: '/home', skeletonId: 'HomeSkeleton' },
          { path: '/login', skeletonId: 'LoginSkeleton' }
        ]
      }
    }),
```

跟你是一样的

**Comment by zhoufanglu** [comment]
> > > ```js
> > > // - Skeleton.js
> > > import Vue from 'vue';
> > > import Skeleton1 from './Skeleton1.vue';
> > > import Skeleton2 from './Skeleton2.vue';
> > > 
> > > export default new Vue({
> > >   components: {
> > >     Skeleton1,
> > >     Skeleton2
> > >   },
> > >  template: `
> > >        <div style='height: 100%;'>
> > >            <Skeleton1 id="skeleton1" style="display:none"/>
> > >            <Skeleton2 id="skeleton2" style="display:none"/>
> > >        </div>
> > >     `
> > > });
> > > ```
> > > 
> > > 
> > > 改成这样试试
> > 
> > 
> > 改成这样 连skeleton组件都不显示了 请问你vue.config怎么写的？
> 
> ```js
>  new SkeletonWebpackPlugin({
>       webpackConfig: {
>         entry: {
>           app: path.join(__dirname, './src/skeleton/entry.ts'),
>         },
>       },
>       minimize: true,
>       router: {
>         mode: 'hash',
>         routes: [
>           { path: '', skeletonId: 'HomeSkeleton' },
>           { path: '/', skeletonId: 'HomeSkeleton' },
>           { path: '/home', skeletonId: 'HomeSkeleton' },
>           { path: '/login', skeletonId: 'LoginSkeleton' }
>         ]
>       }
>     }),
> ```
> 
> 跟你是一样的

老哥 方便加个qq 吗  `735417031`？ 我找不到原因

**Comment by luobinhang** [comment]
你的qq是有验证的





------------------ 原始邮件 ------------------
发件人: "tog"<notifications@github.com>; 
发送时间: 2019年8月5日(星期一) 晚上6:55
收件人: "lavas-project/vue-skeleton-webpack-plugin"<vue-skeleton-webpack-plugin@noreply.github.com>; 
抄送: "阿西"<812428039@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [lavas-project/vue-skeleton-webpack-plugin] 关于vue-cli3 多skeleton 多路由的问题 (#83)



   // - Skeleton.js import Vue from 'vue'; import Skeleton1 from './Skeleton1.vue'; import Skeleton2 from './Skeleton2.vue'; export default new Vue({   components: {     Skeleton1,     Skeleton2   },  template: `        <div style='height: 100%;'>            <Skeleton1 id="skeleton1" style="display:none"/>            <Skeleton2 id="skeleton2" style="display:none"/>        </div>     ` });
 
改成这样试试
  
改成这样 连skeleton组件都不显示了 请问你vue.config怎么写的？
   new SkeletonWebpackPlugin({       webpackConfig: {         entry: {           app: path.join(__dirname, './src/skeleton/entry.ts'),         },       },       minimize: true,       router: {         mode: 'hash',         routes: [           { path: '', skeletonId: 'HomeSkeleton' },           { path: '/', skeletonId: 'HomeSkeleton' },           { path: '/home', skeletonId: 'HomeSkeleton' },           { path: '/login', skeletonId: 'LoginSkeleton' }         ]       }     }),
 
跟你是一样的
  
老哥 方便加个qq 吗  735417031？ 我找不到原因

**Comment by zhoufanglu** [comment]
> 你的qq是有验证的
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "tog"<notifications@github.com>; 发送时间: 2019年8月5日(星期一) 晚上6:55 收件人: "lavas-project/vue-skeleton-webpack-plugin"<vue-skeleton-webpack-plugin@noreply.github.com>; 抄送: "阿西"<812428039@qq.com>; "Comment"<comment@noreply.github.com>; 主题: Re: [lavas-project/vue-skeleton-webpack-plugin] 关于vue-cli3 多skeleton 多路由的问题 (#83) // - Skeleton.js import Vue from 'vue'; import Skeleton1 from './Skeleton1.vue'; import Skeleton2 from './Skeleton2.vue'; export default new Vue({ components: { Skeleton1, Skeleton2 }, template: ` <div style='height: 100%;'> <Skeleton1 id="skeleton1" style="display:none"/> <Skeleton2 id="skeleton2" style="display:none"/> </div> ` }); 改成这样试试 改成这样 连skeleton组件都不显示了 请问你vue.config怎么写的？ new SkeletonWebpackPlugin({ webpackConfig: { entry: { app: path.join(__dirname, './src/skeleton/entry.ts'), }, }, minimize: true, router: { mode: 'hash', routes: [ { path: '', skeletonId: 'HomeSkeleton' }, { path: '/', skeletonId: 'HomeSkeleton' }, { path: '/home', skeletonId: 'HomeSkeleton' }, { path: '/login', skeletonId: 'LoginSkeleton' } ] } }), 跟你是一样的 老哥 方便加个qq 吗 735417031？ 我找不到原因 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

不好意思 答案 是 `卢方舟`

**Comment by zhoufanglu** [comment]
###  原因找到了，上面的`vue.config.js`中配置写错了。路由配置应该和`webpackConfig`同级
```js
config.plugins.push(new SkeletonWebpackPlugin({
      webpackConfig: {
        entry: {
          app: path.join(__dirname, './src/skeleton/entry-skeleton.js'),
        }
      },
      minimize: true,
      quiet: true,
      router: {
        mode: 'hash',
        routes: [
          {
            path: '/home',
            skeletonId: 'skeleton1'
          },
          {
            path: '/test',
            skeletonId: 'skeleton2'
          }
        ]
      }
    }))
```
